name: tests
on: push
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Setup Clojure tools
        uses: DeLaGuardo/setup-clojure@master
        with:
          cli: 1.11.1.1113
      - name: Setup node
        uses: actions/setup-node@v1
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install ws
        run: npm install ws
      - name: Cache m2
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: m2-${{ hashFiles('deps.edn') }}
      - name: Cache gitlibs
        uses: actions/cache@v2
        with:
          path: ~/.gitlibs
          key: gitlibs-${{ hashFiles('deps.edn') }}
      - name: Prepare dependencies
        run: clojure -P -M:test:clj-test:cljs-test
      - name: Run Clojure tests
        run: clojure -X:test:clj-test
      - name: Run ClojureScript tests
        run: clojure -M:test:cljs-test
