name: Tests
on: push
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Setup Clojure tools
        uses: DeLaGuardo/setup-clojure@master
        with:
          tools-deps: 1.10.1.727
      - name: Setup node
        uses: actions/setup-node@v1
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install ws
        run: npm install ws
      - name: Run tests
        run: bin/kaocha --reporter documentation --plugin kaocha.plugin/profiling
